// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

#ifndef PROTOBUF_INCLUDED_Transaction_2eproto
#define PROTOBUF_INCLUDED_Transaction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "TxIn.pb.h"
#include "TxOut.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Transaction_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Transaction_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Transaction_2eproto();
namespace Enze {
class Transaction;
class TransactionDefaultTypeInternal;
extern TransactionDefaultTypeInternal _Transaction_default_instance_;
}  // namespace Enze
namespace google {
namespace protobuf {
template<> ::Enze::Transaction* Arena::CreateMaybeMessage<::Enze::Transaction>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Enze {

// ===================================================================

class Transaction : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Enze.Transaction) */ {
 public:
  Transaction();
  virtual ~Transaction();

  Transaction(const Transaction& from);

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Transaction(Transaction&& from) noexcept
    : Transaction() {
    *this = ::std::move(from);
  }

  inline Transaction& operator=(Transaction&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Transaction& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Transaction* internal_default_instance() {
    return reinterpret_cast<const Transaction*>(
               &_Transaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Transaction* other);
  friend void swap(Transaction& a, Transaction& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Transaction* New() const final {
    return CreateMaybeMessage<Transaction>(NULL);
  }

  Transaction* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Transaction>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Transaction& from);
  void MergeFrom(const Transaction& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Transaction* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Enze.TxIn vTxIn = 3;
  int vtxin_size() const;
  void clear_vtxin();
  static const int kVTxInFieldNumber = 3;
  ::Enze::TxIn* mutable_vtxin(int index);
  ::google::protobuf::RepeatedPtrField< ::Enze::TxIn >*
      mutable_vtxin();
  const ::Enze::TxIn& vtxin(int index) const;
  ::Enze::TxIn* add_vtxin();
  const ::google::protobuf::RepeatedPtrField< ::Enze::TxIn >&
      vtxin() const;

  // repeated .Enze.TxOut vTxOut = 4;
  int vtxout_size() const;
  void clear_vtxout();
  static const int kVTxOutFieldNumber = 4;
  ::Enze::TxOut* mutable_vtxout(int index);
  ::google::protobuf::RepeatedPtrField< ::Enze::TxOut >*
      mutable_vtxout();
  const ::Enze::TxOut& vtxout(int index) const;
  ::Enze::TxOut* add_vtxout();
  const ::google::protobuf::RepeatedPtrField< ::Enze::TxOut >&
      vtxout() const;

  // int32 nCurVersion = 1;
  void clear_ncurversion();
  static const int kNCurVersionFieldNumber = 1;
  ::google::protobuf::int32 ncurversion() const;
  void set_ncurversion(::google::protobuf::int32 value);

  // int32 nLockTime = 2;
  void clear_nlocktime();
  static const int kNLockTimeFieldNumber = 2;
  ::google::protobuf::int32 nlocktime() const;
  void set_nlocktime(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Enze.Transaction)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Enze::TxIn > vtxin_;
  ::google::protobuf::RepeatedPtrField< ::Enze::TxOut > vtxout_;
  ::google::protobuf::int32 ncurversion_;
  ::google::protobuf::int32 nlocktime_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Transaction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Transaction

// int32 nCurVersion = 1;
inline void Transaction::clear_ncurversion() {
  ncurversion_ = 0;
}
inline ::google::protobuf::int32 Transaction::ncurversion() const {
  // @@protoc_insertion_point(field_get:Enze.Transaction.nCurVersion)
  return ncurversion_;
}
inline void Transaction::set_ncurversion(::google::protobuf::int32 value) {
  
  ncurversion_ = value;
  // @@protoc_insertion_point(field_set:Enze.Transaction.nCurVersion)
}

// int32 nLockTime = 2;
inline void Transaction::clear_nlocktime() {
  nlocktime_ = 0;
}
inline ::google::protobuf::int32 Transaction::nlocktime() const {
  // @@protoc_insertion_point(field_get:Enze.Transaction.nLockTime)
  return nlocktime_;
}
inline void Transaction::set_nlocktime(::google::protobuf::int32 value) {
  
  nlocktime_ = value;
  // @@protoc_insertion_point(field_set:Enze.Transaction.nLockTime)
}

// repeated .Enze.TxIn vTxIn = 3;
inline int Transaction::vtxin_size() const {
  return vtxin_.size();
}
inline ::Enze::TxIn* Transaction::mutable_vtxin(int index) {
  // @@protoc_insertion_point(field_mutable:Enze.Transaction.vTxIn)
  return vtxin_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Enze::TxIn >*
Transaction::mutable_vtxin() {
  // @@protoc_insertion_point(field_mutable_list:Enze.Transaction.vTxIn)
  return &vtxin_;
}
inline const ::Enze::TxIn& Transaction::vtxin(int index) const {
  // @@protoc_insertion_point(field_get:Enze.Transaction.vTxIn)
  return vtxin_.Get(index);
}
inline ::Enze::TxIn* Transaction::add_vtxin() {
  // @@protoc_insertion_point(field_add:Enze.Transaction.vTxIn)
  return vtxin_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Enze::TxIn >&
Transaction::vtxin() const {
  // @@protoc_insertion_point(field_list:Enze.Transaction.vTxIn)
  return vtxin_;
}

// repeated .Enze.TxOut vTxOut = 4;
inline int Transaction::vtxout_size() const {
  return vtxout_.size();
}
inline ::Enze::TxOut* Transaction::mutable_vtxout(int index) {
  // @@protoc_insertion_point(field_mutable:Enze.Transaction.vTxOut)
  return vtxout_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Enze::TxOut >*
Transaction::mutable_vtxout() {
  // @@protoc_insertion_point(field_mutable_list:Enze.Transaction.vTxOut)
  return &vtxout_;
}
inline const ::Enze::TxOut& Transaction::vtxout(int index) const {
  // @@protoc_insertion_point(field_get:Enze.Transaction.vTxOut)
  return vtxout_.Get(index);
}
inline ::Enze::TxOut* Transaction::add_vtxout() {
  // @@protoc_insertion_point(field_add:Enze.Transaction.vTxOut)
  return vtxout_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Enze::TxOut >&
Transaction::vtxout() const {
  // @@protoc_insertion_point(field_list:Enze.Transaction.vTxOut)
  return vtxout_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Enze

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Transaction_2eproto
