// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Version.proto

#ifndef PROTOBUF_INCLUDED_Version_2eproto
#define PROTOBUF_INCLUDED_Version_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Address.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Version_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Version_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Version_2eproto();
namespace Enze {
class Version;
class VersionDefaultTypeInternal;
extern VersionDefaultTypeInternal _Version_default_instance_;
}  // namespace Enze
namespace google {
namespace protobuf {
template<> ::Enze::Version* Arena::CreateMaybeMessage<::Enze::Version>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Enze {

// ===================================================================

class Version : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Enze.Version) */ {
 public:
  Version();
  virtual ~Version();

  Version(const Version& from);

  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Version(Version&& from) noexcept
    : Version() {
    *this = ::std::move(from);
  }

  inline Version& operator=(Version&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Version& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Version* internal_default_instance() {
    return reinterpret_cast<const Version*>(
               &_Version_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Version* other);
  friend void swap(Version& a, Version& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Version* New() const final {
    return CreateMaybeMessage<Version>(NULL);
  }

  Version* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Version>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Version* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .Enze.Address addrMe = 4;
  bool has_addrme() const;
  void clear_addrme();
  static const int kAddrMeFieldNumber = 4;
  const ::Enze::Address& addrme() const;
  ::Enze::Address* release_addrme();
  ::Enze::Address* mutable_addrme();
  void set_allocated_addrme(::Enze::Address* addrme);

  // int64 uTime = 1;
  void clear_utime();
  static const int kUTimeFieldNumber = 1;
  ::google::protobuf::int64 utime() const;
  void set_utime(::google::protobuf::int64 value);

  // uint64 nServices = 3;
  void clear_nservices();
  static const int kNServicesFieldNumber = 3;
  ::google::protobuf::uint64 nservices() const;
  void set_nservices(::google::protobuf::uint64 value);

  // int32 nVersion = 2;
  void clear_nversion();
  static const int kNVersionFieldNumber = 2;
  ::google::protobuf::int32 nversion() const;
  void set_nversion(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Enze.Version)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::Enze::Address* addrme_;
  ::google::protobuf::int64 utime_;
  ::google::protobuf::uint64 nservices_;
  ::google::protobuf::int32 nversion_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Version_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Version

// int64 uTime = 1;
inline void Version::clear_utime() {
  utime_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 Version::utime() const {
  // @@protoc_insertion_point(field_get:Enze.Version.uTime)
  return utime_;
}
inline void Version::set_utime(::google::protobuf::int64 value) {
  
  utime_ = value;
  // @@protoc_insertion_point(field_set:Enze.Version.uTime)
}

// int32 nVersion = 2;
inline void Version::clear_nversion() {
  nversion_ = 0;
}
inline ::google::protobuf::int32 Version::nversion() const {
  // @@protoc_insertion_point(field_get:Enze.Version.nVersion)
  return nversion_;
}
inline void Version::set_nversion(::google::protobuf::int32 value) {
  
  nversion_ = value;
  // @@protoc_insertion_point(field_set:Enze.Version.nVersion)
}

// uint64 nServices = 3;
inline void Version::clear_nservices() {
  nservices_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Version::nservices() const {
  // @@protoc_insertion_point(field_get:Enze.Version.nServices)
  return nservices_;
}
inline void Version::set_nservices(::google::protobuf::uint64 value) {
  
  nservices_ = value;
  // @@protoc_insertion_point(field_set:Enze.Version.nServices)
}

// .Enze.Address addrMe = 4;
inline bool Version::has_addrme() const {
  return this != internal_default_instance() && addrme_ != NULL;
}
inline const ::Enze::Address& Version::addrme() const {
  const ::Enze::Address* p = addrme_;
  // @@protoc_insertion_point(field_get:Enze.Version.addrMe)
  return p != NULL ? *p : *reinterpret_cast<const ::Enze::Address*>(
      &::Enze::_Address_default_instance_);
}
inline ::Enze::Address* Version::release_addrme() {
  // @@protoc_insertion_point(field_release:Enze.Version.addrMe)
  
  ::Enze::Address* temp = addrme_;
  addrme_ = NULL;
  return temp;
}
inline ::Enze::Address* Version::mutable_addrme() {
  
  if (addrme_ == NULL) {
    auto* p = CreateMaybeMessage<::Enze::Address>(GetArenaNoVirtual());
    addrme_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Enze.Version.addrMe)
  return addrme_;
}
inline void Version::set_allocated_addrme(::Enze::Address* addrme) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(addrme_);
  }
  if (addrme) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      addrme = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, addrme, submessage_arena);
    }
    
  } else {
    
  }
  addrme_ = addrme;
  // @@protoc_insertion_point(field_set_allocated:Enze.Version.addrMe)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Enze

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Version_2eproto
