// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiskBlockIndex.proto

#include "DiskBlockIndex.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace Enze {
class DiskBlockIndexDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DiskBlockIndex> _instance;
} _DiskBlockIndex_default_instance_;
}  // namespace Enze
static void InitDefaultsDiskBlockIndex_DiskBlockIndex_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Enze::_DiskBlockIndex_default_instance_;
    new (ptr) ::Enze::DiskBlockIndex();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Enze::DiskBlockIndex::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DiskBlockIndex_DiskBlockIndex_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDiskBlockIndex_DiskBlockIndex_2eproto}, {}};

void InitDefaults_DiskBlockIndex_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_DiskBlockIndex_DiskBlockIndex_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_DiskBlockIndex_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_DiskBlockIndex_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_DiskBlockIndex_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_DiskBlockIndex_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, hashnext_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, hashprev_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, nfile_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, nblockpos_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, nheight_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, nversion_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, ntime_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, nbit_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, nnonce_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskBlockIndex, hashmerkleroot_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Enze::DiskBlockIndex)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Enze::_DiskBlockIndex_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_DiskBlockIndex_2eproto = {
  {}, AddDescriptors_DiskBlockIndex_2eproto, "DiskBlockIndex.proto", schemas,
  file_default_instances, TableStruct_DiskBlockIndex_2eproto::offsets,
  file_level_metadata_DiskBlockIndex_2eproto, 1, file_level_enum_descriptors_DiskBlockIndex_2eproto, file_level_service_descriptors_DiskBlockIndex_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_DiskBlockIndex_2eproto = {
  false, InitDefaults_DiskBlockIndex_2eproto, 
  "\n\024DiskBlockIndex.proto\022\004Enze\"\276\001\n\016DiskBlo"
  "ckIndex\022\020\n\010hashNext\030\001 \001(\014\022\020\n\010hashPrev\030\002 "
  "\001(\014\022\r\n\005nFile\030\003 \001(\r\022\021\n\tnBlockpos\030\004 \001(\r\022\017\n"
  "\007nHeight\030\005 \001(\r\022\020\n\010nVersion\030\006 \001(\r\022\r\n\005nTim"
  "e\030\007 \001(\r\022\014\n\004nBit\030\010 \001(\r\022\016\n\006nNonce\030\t \001(\r\022\026\n"
  "\016hashMerkleRoot\030\n \001(\014b\006proto3"
,
  "DiskBlockIndex.proto", &assign_descriptors_table_DiskBlockIndex_2eproto, 229,
};

void AddDescriptors_DiskBlockIndex_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_DiskBlockIndex_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_DiskBlockIndex_2eproto = []() { AddDescriptors_DiskBlockIndex_2eproto(); return true; }();
namespace Enze {

// ===================================================================

void DiskBlockIndex::InitAsDefaultInstance() {
}
class DiskBlockIndex::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DiskBlockIndex::kHashNextFieldNumber;
const int DiskBlockIndex::kHashPrevFieldNumber;
const int DiskBlockIndex::kNFileFieldNumber;
const int DiskBlockIndex::kNBlockposFieldNumber;
const int DiskBlockIndex::kNHeightFieldNumber;
const int DiskBlockIndex::kNVersionFieldNumber;
const int DiskBlockIndex::kNTimeFieldNumber;
const int DiskBlockIndex::kNBitFieldNumber;
const int DiskBlockIndex::kNNonceFieldNumber;
const int DiskBlockIndex::kHashMerkleRootFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DiskBlockIndex::DiskBlockIndex()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Enze.DiskBlockIndex)
}
DiskBlockIndex::DiskBlockIndex(const DiskBlockIndex& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hashnext_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hashnext().size() > 0) {
    hashnext_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hashnext_);
  }
  hashprev_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hashprev().size() > 0) {
    hashprev_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hashprev_);
  }
  hashmerkleroot_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hashmerkleroot().size() > 0) {
    hashmerkleroot_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hashmerkleroot_);
  }
  ::memcpy(&nfile_, &from.nfile_,
    static_cast<size_t>(reinterpret_cast<char*>(&nnonce_) -
    reinterpret_cast<char*>(&nfile_)) + sizeof(nnonce_));
  // @@protoc_insertion_point(copy_constructor:Enze.DiskBlockIndex)
}

void DiskBlockIndex::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DiskBlockIndex_DiskBlockIndex_2eproto.base);
  hashnext_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hashprev_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hashmerkleroot_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&nfile_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nnonce_) -
      reinterpret_cast<char*>(&nfile_)) + sizeof(nnonce_));
}

DiskBlockIndex::~DiskBlockIndex() {
  // @@protoc_insertion_point(destructor:Enze.DiskBlockIndex)
  SharedDtor();
}

void DiskBlockIndex::SharedDtor() {
  hashnext_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hashprev_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hashmerkleroot_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DiskBlockIndex::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DiskBlockIndex& DiskBlockIndex::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DiskBlockIndex_DiskBlockIndex_2eproto.base);
  return *internal_default_instance();
}


void DiskBlockIndex::Clear() {
// @@protoc_insertion_point(message_clear_start:Enze.DiskBlockIndex)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hashnext_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hashprev_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hashmerkleroot_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&nfile_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nnonce_) -
      reinterpret_cast<char*>(&nfile_)) + sizeof(nnonce_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DiskBlockIndex::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DiskBlockIndex*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bytes hashNext = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::google::protobuf::internal::StringParser;
        ::std::string* str = msg->mutable_hashnext();
        str->clear();
        object = str;
        if (size > end - ptr) goto len_delim_till_end;
        str->append(ptr, size);
        ptr += size;
        break;
      }
      // bytes hashPrev = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::google::protobuf::internal::StringParser;
        ::std::string* str = msg->mutable_hashprev();
        str->clear();
        object = str;
        if (size > end - ptr) goto len_delim_till_end;
        str->append(ptr, size);
        ptr += size;
        break;
      }
      // uint32 nFile = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nfile(value);
        break;
      }
      // uint32 nBlockpos = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nblockpos(value);
        break;
      }
      // uint32 nHeight = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nheight(value);
        break;
      }
      // uint32 nVersion = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 48) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nversion(value);
        break;
      }
      // uint32 nTime = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 56) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_ntime(value);
        break;
      }
      // uint32 nBit = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 64) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nbit(value);
        break;
      }
      // uint32 nNonce = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 72) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nnonce(value);
        break;
      }
      // bytes hashMerkleRoot = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 82) goto handle_unusual;
        ptr = Varint::Parse32Inline(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::google::protobuf::internal::StringParser;
        ::std::string* str = msg->mutable_hashmerkleroot();
        str->clear();
        object = str;
        if (size > end - ptr) goto len_delim_till_end;
        str->append(ptr, size);
        ptr += size;
        break;
      }
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4 || tag == 0) {
          bool ok = ctx->ValidEndGroup(tag);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DiskBlockIndex::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Enze.DiskBlockIndex)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes hashNext = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hashnext()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes hashPrev = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hashprev()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nFile = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nfile_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nBlockpos = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nblockpos_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nHeight = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nheight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nVersion = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (48 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nTime = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (56 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ntime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nBit = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (64 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nbit_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nNonce = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (72 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nnonce_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes hashMerkleRoot = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (82 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hashmerkleroot()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Enze.DiskBlockIndex)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Enze.DiskBlockIndex)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DiskBlockIndex::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Enze.DiskBlockIndex)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes hashNext = 1;
  if (this->hashnext().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->hashnext(), output);
  }

  // bytes hashPrev = 2;
  if (this->hashprev().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->hashprev(), output);
  }

  // uint32 nFile = 3;
  if (this->nfile() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->nfile(), output);
  }

  // uint32 nBlockpos = 4;
  if (this->nblockpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->nblockpos(), output);
  }

  // uint32 nHeight = 5;
  if (this->nheight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->nheight(), output);
  }

  // uint32 nVersion = 6;
  if (this->nversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->nversion(), output);
  }

  // uint32 nTime = 7;
  if (this->ntime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->ntime(), output);
  }

  // uint32 nBit = 8;
  if (this->nbit() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->nbit(), output);
  }

  // uint32 nNonce = 9;
  if (this->nnonce() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->nnonce(), output);
  }

  // bytes hashMerkleRoot = 10;
  if (this->hashmerkleroot().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      10, this->hashmerkleroot(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Enze.DiskBlockIndex)
}

::google::protobuf::uint8* DiskBlockIndex::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Enze.DiskBlockIndex)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes hashNext = 1;
  if (this->hashnext().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->hashnext(), target);
  }

  // bytes hashPrev = 2;
  if (this->hashprev().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->hashprev(), target);
  }

  // uint32 nFile = 3;
  if (this->nfile() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->nfile(), target);
  }

  // uint32 nBlockpos = 4;
  if (this->nblockpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->nblockpos(), target);
  }

  // uint32 nHeight = 5;
  if (this->nheight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->nheight(), target);
  }

  // uint32 nVersion = 6;
  if (this->nversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->nversion(), target);
  }

  // uint32 nTime = 7;
  if (this->ntime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->ntime(), target);
  }

  // uint32 nBit = 8;
  if (this->nbit() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->nbit(), target);
  }

  // uint32 nNonce = 9;
  if (this->nnonce() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->nnonce(), target);
  }

  // bytes hashMerkleRoot = 10;
  if (this->hashmerkleroot().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        10, this->hashmerkleroot(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Enze.DiskBlockIndex)
  return target;
}

size_t DiskBlockIndex::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Enze.DiskBlockIndex)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes hashNext = 1;
  if (this->hashnext().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->hashnext());
  }

  // bytes hashPrev = 2;
  if (this->hashprev().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->hashprev());
  }

  // bytes hashMerkleRoot = 10;
  if (this->hashmerkleroot().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->hashmerkleroot());
  }

  // uint32 nFile = 3;
  if (this->nfile() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nfile());
  }

  // uint32 nBlockpos = 4;
  if (this->nblockpos() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nblockpos());
  }

  // uint32 nHeight = 5;
  if (this->nheight() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nheight());
  }

  // uint32 nVersion = 6;
  if (this->nversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nversion());
  }

  // uint32 nTime = 7;
  if (this->ntime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ntime());
  }

  // uint32 nBit = 8;
  if (this->nbit() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nbit());
  }

  // uint32 nNonce = 9;
  if (this->nnonce() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nnonce());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DiskBlockIndex::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Enze.DiskBlockIndex)
  GOOGLE_DCHECK_NE(&from, this);
  const DiskBlockIndex* source =
      ::google::protobuf::DynamicCastToGenerated<DiskBlockIndex>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Enze.DiskBlockIndex)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Enze.DiskBlockIndex)
    MergeFrom(*source);
  }
}

void DiskBlockIndex::MergeFrom(const DiskBlockIndex& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Enze.DiskBlockIndex)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.hashnext().size() > 0) {

    hashnext_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hashnext_);
  }
  if (from.hashprev().size() > 0) {

    hashprev_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hashprev_);
  }
  if (from.hashmerkleroot().size() > 0) {

    hashmerkleroot_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hashmerkleroot_);
  }
  if (from.nfile() != 0) {
    set_nfile(from.nfile());
  }
  if (from.nblockpos() != 0) {
    set_nblockpos(from.nblockpos());
  }
  if (from.nheight() != 0) {
    set_nheight(from.nheight());
  }
  if (from.nversion() != 0) {
    set_nversion(from.nversion());
  }
  if (from.ntime() != 0) {
    set_ntime(from.ntime());
  }
  if (from.nbit() != 0) {
    set_nbit(from.nbit());
  }
  if (from.nnonce() != 0) {
    set_nnonce(from.nnonce());
  }
}

void DiskBlockIndex::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Enze.DiskBlockIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiskBlockIndex::CopyFrom(const DiskBlockIndex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Enze.DiskBlockIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiskBlockIndex::IsInitialized() const {
  return true;
}

void DiskBlockIndex::Swap(DiskBlockIndex* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DiskBlockIndex::InternalSwap(DiskBlockIndex* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  hashnext_.Swap(&other->hashnext_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hashprev_.Swap(&other->hashprev_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hashmerkleroot_.Swap(&other->hashmerkleroot_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(nfile_, other->nfile_);
  swap(nblockpos_, other->nblockpos_);
  swap(nheight_, other->nheight_);
  swap(nversion_, other->nversion_);
  swap(ntime_, other->ntime_);
  swap(nbit_, other->nbit_);
  swap(nnonce_, other->nnonce_);
}

::google::protobuf::Metadata DiskBlockIndex::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_DiskBlockIndex_2eproto);
  return ::file_level_metadata_DiskBlockIndex_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Enze
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::Enze::DiskBlockIndex* Arena::CreateMaybeMessage< ::Enze::DiskBlockIndex >(Arena* arena) {
  return Arena::CreateInternal< ::Enze::DiskBlockIndex >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
