// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiskTxPos.proto

#include "DiskTxPos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace Enze {
class DiskTxPosDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DiskTxPos> _instance;
} _DiskTxPos_default_instance_;
}  // namespace Enze
static void InitDefaultsDiskTxPos_DiskTxPos_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Enze::_DiskTxPos_default_instance_;
    new (ptr) ::Enze::DiskTxPos();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Enze::DiskTxPos::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DiskTxPos_DiskTxPos_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDiskTxPos_DiskTxPos_2eproto}, {}};

void InitDefaults_DiskTxPos_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_DiskTxPos_DiskTxPos_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_DiskTxPos_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_DiskTxPos_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_DiskTxPos_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_DiskTxPos_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Enze::DiskTxPos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Enze::DiskTxPos, nfile_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskTxPos, nblockpos_),
  PROTOBUF_FIELD_OFFSET(::Enze::DiskTxPos, ntxpos_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Enze::DiskTxPos)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Enze::_DiskTxPos_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_DiskTxPos_2eproto = {
  {}, AddDescriptors_DiskTxPos_2eproto, "DiskTxPos.proto", schemas,
  file_default_instances, TableStruct_DiskTxPos_2eproto::offsets,
  file_level_metadata_DiskTxPos_2eproto, 1, file_level_enum_descriptors_DiskTxPos_2eproto, file_level_service_descriptors_DiskTxPos_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_DiskTxPos_2eproto = {
  false, InitDefaults_DiskTxPos_2eproto, 
  "\n\017DiskTxPos.proto\022\004Enze\"=\n\tDiskTxPos\022\r\n\005"
  "nFile\030\001 \001(\r\022\021\n\tnBlockPos\030\002 \001(\r\022\016\n\006nTxPos"
  "\030\003 \001(\rb\006proto3"
,
  "DiskTxPos.proto", &assign_descriptors_table_DiskTxPos_2eproto, 94,
};

void AddDescriptors_DiskTxPos_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_DiskTxPos_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_DiskTxPos_2eproto = []() { AddDescriptors_DiskTxPos_2eproto(); return true; }();
namespace Enze {

// ===================================================================

void DiskTxPos::InitAsDefaultInstance() {
}
class DiskTxPos::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DiskTxPos::kNFileFieldNumber;
const int DiskTxPos::kNBlockPosFieldNumber;
const int DiskTxPos::kNTxPosFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DiskTxPos::DiskTxPos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Enze.DiskTxPos)
}
DiskTxPos::DiskTxPos(const DiskTxPos& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&nfile_, &from.nfile_,
    static_cast<size_t>(reinterpret_cast<char*>(&ntxpos_) -
    reinterpret_cast<char*>(&nfile_)) + sizeof(ntxpos_));
  // @@protoc_insertion_point(copy_constructor:Enze.DiskTxPos)
}

void DiskTxPos::SharedCtor() {
  ::memset(&nfile_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ntxpos_) -
      reinterpret_cast<char*>(&nfile_)) + sizeof(ntxpos_));
}

DiskTxPos::~DiskTxPos() {
  // @@protoc_insertion_point(destructor:Enze.DiskTxPos)
  SharedDtor();
}

void DiskTxPos::SharedDtor() {
}

void DiskTxPos::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DiskTxPos& DiskTxPos::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DiskTxPos_DiskTxPos_2eproto.base);
  return *internal_default_instance();
}


void DiskTxPos::Clear() {
// @@protoc_insertion_point(message_clear_start:Enze.DiskTxPos)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&nfile_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ntxpos_) -
      reinterpret_cast<char*>(&nfile_)) + sizeof(ntxpos_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DiskTxPos::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DiskTxPos*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint32 nFile = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nfile(value);
        break;
      }
      // uint32 nBlockPos = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_nblockpos(value);
        break;
      }
      // uint32 nTxPos = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = Varint::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::uint32 value = val;
        msg->set_ntxpos(value);
        break;
      }
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4 || tag == 0) {
          bool ok = ctx->ValidEndGroup(tag);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ok);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DiskTxPos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Enze.DiskTxPos)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 nFile = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nfile_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nBlockPos = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nblockpos_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nTxPos = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ntxpos_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Enze.DiskTxPos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Enze.DiskTxPos)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DiskTxPos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Enze.DiskTxPos)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 nFile = 1;
  if (this->nfile() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->nfile(), output);
  }

  // uint32 nBlockPos = 2;
  if (this->nblockpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->nblockpos(), output);
  }

  // uint32 nTxPos = 3;
  if (this->ntxpos() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->ntxpos(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Enze.DiskTxPos)
}

::google::protobuf::uint8* DiskTxPos::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Enze.DiskTxPos)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 nFile = 1;
  if (this->nfile() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->nfile(), target);
  }

  // uint32 nBlockPos = 2;
  if (this->nblockpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->nblockpos(), target);
  }

  // uint32 nTxPos = 3;
  if (this->ntxpos() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->ntxpos(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Enze.DiskTxPos)
  return target;
}

size_t DiskTxPos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Enze.DiskTxPos)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 nFile = 1;
  if (this->nfile() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nfile());
  }

  // uint32 nBlockPos = 2;
  if (this->nblockpos() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nblockpos());
  }

  // uint32 nTxPos = 3;
  if (this->ntxpos() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ntxpos());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DiskTxPos::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Enze.DiskTxPos)
  GOOGLE_DCHECK_NE(&from, this);
  const DiskTxPos* source =
      ::google::protobuf::DynamicCastToGenerated<DiskTxPos>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Enze.DiskTxPos)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Enze.DiskTxPos)
    MergeFrom(*source);
  }
}

void DiskTxPos::MergeFrom(const DiskTxPos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Enze.DiskTxPos)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nfile() != 0) {
    set_nfile(from.nfile());
  }
  if (from.nblockpos() != 0) {
    set_nblockpos(from.nblockpos());
  }
  if (from.ntxpos() != 0) {
    set_ntxpos(from.ntxpos());
  }
}

void DiskTxPos::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Enze.DiskTxPos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiskTxPos::CopyFrom(const DiskTxPos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Enze.DiskTxPos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiskTxPos::IsInitialized() const {
  return true;
}

void DiskTxPos::Swap(DiskTxPos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DiskTxPos::InternalSwap(DiskTxPos* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(nfile_, other->nfile_);
  swap(nblockpos_, other->nblockpos_);
  swap(ntxpos_, other->ntxpos_);
}

::google::protobuf::Metadata DiskTxPos::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_DiskTxPos_2eproto);
  return ::file_level_metadata_DiskTxPos_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Enze
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::Enze::DiskTxPos* Arena::CreateMaybeMessage< ::Enze::DiskTxPos >(Arena* arena) {
  return Arena::CreateInternal< ::Enze::DiskTxPos >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
