// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TxIndex.proto

#ifndef PROTOBUF_INCLUDED_TxIndex_2eproto
#define PROTOBUF_INCLUDED_TxIndex_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "DiskTxPos.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TxIndex_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_TxIndex_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_TxIndex_2eproto();
namespace Enze {
class TxIndex;
class TxIndexDefaultTypeInternal;
extern TxIndexDefaultTypeInternal _TxIndex_default_instance_;
}  // namespace Enze
namespace google {
namespace protobuf {
template<> ::Enze::TxIndex* Arena::CreateMaybeMessage<::Enze::TxIndex>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Enze {

// ===================================================================

class TxIndex : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Enze.TxIndex) */ {
 public:
  TxIndex();
  virtual ~TxIndex();

  TxIndex(const TxIndex& from);

  inline TxIndex& operator=(const TxIndex& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TxIndex(TxIndex&& from) noexcept
    : TxIndex() {
    *this = ::std::move(from);
  }

  inline TxIndex& operator=(TxIndex&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TxIndex& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TxIndex* internal_default_instance() {
    return reinterpret_cast<const TxIndex*>(
               &_TxIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TxIndex* other);
  friend void swap(TxIndex& a, TxIndex& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TxIndex* New() const final {
    return CreateMaybeMessage<TxIndex>(NULL);
  }

  TxIndex* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TxIndex>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TxIndex& from);
  void MergeFrom(const TxIndex& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TxIndex* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Enze.DiskTxPos vSpent = 2;
  int vspent_size() const;
  void clear_vspent();
  static const int kVSpentFieldNumber = 2;
  ::Enze::DiskTxPos* mutable_vspent(int index);
  ::google::protobuf::RepeatedPtrField< ::Enze::DiskTxPos >*
      mutable_vspent();
  const ::Enze::DiskTxPos& vspent(int index) const;
  ::Enze::DiskTxPos* add_vspent();
  const ::google::protobuf::RepeatedPtrField< ::Enze::DiskTxPos >&
      vspent() const;

  // .Enze.DiskTxPos cDiskPos = 1;
  bool has_cdiskpos() const;
  void clear_cdiskpos();
  static const int kCDiskPosFieldNumber = 1;
  const ::Enze::DiskTxPos& cdiskpos() const;
  ::Enze::DiskTxPos* release_cdiskpos();
  ::Enze::DiskTxPos* mutable_cdiskpos();
  void set_allocated_cdiskpos(::Enze::DiskTxPos* cdiskpos);

  // @@protoc_insertion_point(class_scope:Enze.TxIndex)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Enze::DiskTxPos > vspent_;
  ::Enze::DiskTxPos* cdiskpos_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_TxIndex_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TxIndex

// .Enze.DiskTxPos cDiskPos = 1;
inline bool TxIndex::has_cdiskpos() const {
  return this != internal_default_instance() && cdiskpos_ != NULL;
}
inline const ::Enze::DiskTxPos& TxIndex::cdiskpos() const {
  const ::Enze::DiskTxPos* p = cdiskpos_;
  // @@protoc_insertion_point(field_get:Enze.TxIndex.cDiskPos)
  return p != NULL ? *p : *reinterpret_cast<const ::Enze::DiskTxPos*>(
      &::Enze::_DiskTxPos_default_instance_);
}
inline ::Enze::DiskTxPos* TxIndex::release_cdiskpos() {
  // @@protoc_insertion_point(field_release:Enze.TxIndex.cDiskPos)
  
  ::Enze::DiskTxPos* temp = cdiskpos_;
  cdiskpos_ = NULL;
  return temp;
}
inline ::Enze::DiskTxPos* TxIndex::mutable_cdiskpos() {
  
  if (cdiskpos_ == NULL) {
    auto* p = CreateMaybeMessage<::Enze::DiskTxPos>(GetArenaNoVirtual());
    cdiskpos_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Enze.TxIndex.cDiskPos)
  return cdiskpos_;
}
inline void TxIndex::set_allocated_cdiskpos(::Enze::DiskTxPos* cdiskpos) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(cdiskpos_);
  }
  if (cdiskpos) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      cdiskpos = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, cdiskpos, submessage_arena);
    }
    
  } else {
    
  }
  cdiskpos_ = cdiskpos;
  // @@protoc_insertion_point(field_set_allocated:Enze.TxIndex.cDiskPos)
}

// repeated .Enze.DiskTxPos vSpent = 2;
inline int TxIndex::vspent_size() const {
  return vspent_.size();
}
inline ::Enze::DiskTxPos* TxIndex::mutable_vspent(int index) {
  // @@protoc_insertion_point(field_mutable:Enze.TxIndex.vSpent)
  return vspent_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Enze::DiskTxPos >*
TxIndex::mutable_vspent() {
  // @@protoc_insertion_point(field_mutable_list:Enze.TxIndex.vSpent)
  return &vspent_;
}
inline const ::Enze::DiskTxPos& TxIndex::vspent(int index) const {
  // @@protoc_insertion_point(field_get:Enze.TxIndex.vSpent)
  return vspent_.Get(index);
}
inline ::Enze::DiskTxPos* TxIndex::add_vspent() {
  // @@protoc_insertion_point(field_add:Enze.TxIndex.vSpent)
  return vspent_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Enze::DiskTxPos >&
TxIndex::vspent() const {
  // @@protoc_insertion_point(field_list:Enze.TxIndex.vSpent)
  return vspent_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Enze

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_TxIndex_2eproto
